all:
  hosts:
    reddit-app:
  children:
    app:
      hosts:
        reddit-app:
          ansible_host: 51.250.83.127
      vars:
         ansible_port: 22
    db:
      hosts:
        reddit-db:
          ansible_host: 51.250.6.237
