all:
  hosts:
    reddit-app:
  children:
    app:
      hosts:
        reddit-app:
          ansible_host: 158.160.50.5
      vars:
         ansible_port: 22
    db:
      hosts:
        reddit-db:
          ansible_host: 51.250.67.7
