---
- name: Install MongoDB
  hosts: all
  become: true
  tasks:
  - name: Add python APT repository
    apt_repository:
      repo: ppa:deadsnakes/ppa
      state: present
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Install python
    apt: "name=python state=present"
  - name: Install MongoDB Server
    apt:
      name: mongodb-server
      state: present
  - name: Enable MongoDB
    service: name=mongodb state=started
