---
- name: Install ruby and rubygems
  apt: "name={{ item }} state=present"
  with_items:
    - dialog
    - rsync
    - dos2unix
    - git
    - telnet
    - ruby-full
    - ruby-bundler
    - build-essential
  tags: ruby
