all:
  hosts:
    reddit-app:
  children:
    app:
      hosts:
        reddit-app:
          ansible_host: 158.160.33.234
      vars:
         ansible_port: 22
    db:
      hosts:
        reddit-db:
          ansible_host: 62.84.124.68
